#!/bin/bash
# ============================================================================
# Run HARM assertion mining (Part 3)
# Requires: HARM tool (https://github.com/SamueleGerminiani/harm)
# ============================================================================
set -e

PROJ_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HARM_DIR="$PROJ_ROOT/5_harm"
VCD_DIR="$PROJ_ROOT/6_vcd_traces"

echo "============================================"
echo " Part 3 – HARM Assertion Mining"
echo "============================================"

# Look for HARM: first on PATH, then in local build directory
HARM_BIN=""
if command -v harm &> /dev/null; then
    HARM_BIN="harm"
elif [ -x "$PROJ_ROOT/harm/build/harm" ]; then
    HARM_BIN="$PROJ_ROOT/harm/build/harm"
    export LD_LIBRARY_PATH="$PROJ_ROOT/harm/build/third_party/antlr4/lib:$LD_LIBRARY_PATH"
else
    echo "[ERROR] 'harm' not found on PATH or in $PROJ_ROOT/harm/build/"
    echo "        Install from: https://github.com/SamueleGerminiani/harm"
    echo ""
    echo "  Quick install:"
    echo "    cd $PROJ_ROOT"
    echo "    git clone https://github.com/SamueleGerminiani/harm.git"
    echo "    cd harm/third_party && bash install_all.sh && cd .."
    echo "    mkdir build && cd build"
    echo "    cmake -DCMAKE_BUILD_TYPE=Release .."
    echo "    make"
    echo ""
    exit 1
fi

echo "[INFO] Using HARM: $HARM_BIN"
echo "[INFO] Running HARM on vending_machine.vcd ..."

# Use the VCD scope from the simple TB trace: tb_vending_machine::DUT
# (The VCD was generated by tb_vending_machine.sv, not tbench_top.sv)
# HARM uses "::" as the scope separator (see --vcd-ss docs).
"$HARM_BIN" \
    --vcd "$VCD_DIR/vending_machine.vcd" \
    --clk clk \
    --conf "$HARM_DIR/vending_machine_harm.xml" \
    --vcd-ss "tb_vending_machine::DUT" \
    --sva \
    --force-int \
    --dump-to "$HARM_DIR/mined_assertions_dump.txt" \
    2>&1 | tee "$HARM_DIR/harm_log.txt"

echo ""
echo "============================================"
echo " Done. Mined assertions saved to:"
echo "   $HARM_DIR/mined_assertions_dump.txt"
echo " Full log saved to:"
echo "   $HARM_DIR/harm_log.txt"
echo "============================================"
